services:
    redis:
        container_name: '${NAME}-redis'
        image: 'redis:alpine'
        command:
            - redis-server
            - '--maxmemory 128mb'
            - '--maxmemory-policy volatile-lru'
            - '--save ""'
    db:
        container_name: '${NAME}-db'
        image: 'mariadb:10.11'
        working_dir: /application
        command:
            - mysqld
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
            - '--innodb-file-per-table=1'
        volumes:
            - 'pimcore-database:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=ROOT
            - MYSQL_DATABASE=pimcore
            - MYSQL_USER=pimcore
            - MYSQL_PASSWORD=pimcore
        healthcheck:
            test: [ CMD-SHELL, "mysql -h db -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE -e 'SHOW TABLES;'" ]
            interval: 10s
            retries: 6
            start_period: 1m
            timeout: 3s

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 3322:80
        environment:
            - PMA_ARBITRARY=1
    nginx:
        container_name: '${NAME}-nginx'
        image: 'nginx:stable-alpine'
        volumes:
            - '.:/var/www/html:ro'
            - './.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
        depends_on:
            - php
        environment:
            VIRTUAL_HOST: '${NAME}.local'
            VIRTUAL_PORT: '80'
        links:
            - 'php:php'
        ports:
            - "8989:80"
    php:
        container_name: '${NAME}-php'
        user: '1000:1000'
        image: 'pimcore/pimcore:php8.2-debug-latest'
        environment:
            COMPOSER_HOME: /var/www/html
            PHP_IDE_CONFIG: serverName=localhost
            PIMCORE_INSTALL_MYSQL_USERNAME: pimcore
            PIMCORE_INSTALL_MYSQL_PASSWORD: pimcore
            PIMCORE_INSTALL_MYSQL_PORT: 3306
            PIMCORE_INSTALL_MYSQL_HOST_SOCKET: db
            PIMCORE_INSTALL_MYSQL_DATABASE: pimcore
        depends_on:
            db: { condition: service_healthy }
        volumes:
            - '.:/var/www/html'
        links:
            - 'db:db'
            - 'redis:redis'
    supervisord:
        container_name: '${NAME}-supervisord'
        user: '1000:1000'
        image: 'pimcore/pimcore:php8.2-supervisord-latest'
        depends_on:
            db: { condition: service_healthy }
        volumes:
            - '.:/var/www/html'
            - './.docker/supervisord.conf:/etc/supervisor/conf.d/pimcore.conf:ro'
        links:
            - 'db:db'
    test-db:
        container_name: '${NAME}-test-db'
        profiles:
            - test
        extends: db
        volumes:
            - 'pimcore-test-database:/var/lib/mysql'
    test-php:
        container_name: '${NAME}-test-php'
        profiles:
            - test
        extends: php
        environment:
            APP_ENV: test
            PIMCORE_TEST_DB_DSN: '${PIMCORE_TEST_DB_DSN:-mysql://pimcore:pimcore@test-db/pimcore}'
            PIMCORE_INSTALL_ADMIN_USERNAME: pimcore
            PIMCORE_INSTALL_ADMIN_PASSWORD: pimcore
            PIMCORE_INSTALL_MYSQL_HOST_SOCKET: test-db
        depends_on:
            test-db: { condition: service_healthy }
        volumes:
            - 'pimcore-test-var:/var/www/html/var'
            - 'pimcore-test-public-var:/var/www/html/public/var'
volumes:
    pimcore-database: null
    pimcore-test-database: null
    pimcore-test-var: null
    pimcore-test-public-var: null
networks:
    default:
        name: nginx-proxy
        external: 'true'
