pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    default:
                        items: {  }
                        medias: {  }
                        name: default
                        description: ''
                        group: ''
                        format: ORIGINAL
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: true
                        modificationDate: 1700395070
                        creationDate: 1700394434
                        preserveAnimation: false
