---
name: Deploy Prod

on:
    push:
        branches:
            - main

jobs:
    deploy-be:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4 # @see: https://github.com/actions/checkout

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with: { php-version: "8.2" }

            - name: Deploy
              uses: deployphp/action@v1.0.17 # @see: https://github.com/deployphp/action
              with:
                  private-key: "${{ secrets.PRIVATE_KEY }}"
                  dep: deploy prod
